export enum AppPrivilege {
    CREATE_USER = "CREATE_USER",
    UPDATE_USER = "UPDATE_USER",
    ACTIVATE_USER = "ACTIVATE_USER",
    DEACTIVATE_USER = "DEACTIVATE_USER",
    REVIEW_CREATE_USER = "REVIEW_CREATE_USER",
    REVIEW_UPDATE_USER = "REVIEW_UPDATE_USER",
    REVIEW_ACTIVATE_USER = "REVIEW_ACTIVATE_USER",
    REVIEW_DEACTIVATE_USER = "REVIEW_DEACTIVATE_USER",

    CREATE_USER_GROUP = "CREATE_USER_GROUP",
    UPDATE_USER_GROUP = "UPDATE_USER_GROUP",
    ACTIVATE_USER_GROUP = "ACTIVATE_USER_GROUP",
    DEACTIVATE_USER_GROUP = "DEACTIVATE_USER_GROUP",
    REVIEW_CREATE_USER_GROUP = "REVIEW_CREATE_USER_GROUP",
    REVIEW_UPDATE_USER_GROUP = "REVIEW_UPDATE_USER_GROUP",
    REVIEW_ACTIVATE_USER_GROUP = "REVIEW_ACTIVATE_USER_GROUP",
    REVIEW_DEACTIVATE_USER_GROUP = "REVIEW_DEACTIVATE_USER_GROUP",
    
    VIEW_ACTIVITY_LOGS = "VIEW_ACTIVITY_LOGS"
}